export const SET_USER = 'SET_USER';
export const LOG_OUT = 'LOG_OUT';

export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const SET_WATCHLIST_NAME = 'SET_WATCHLIST_NAME';
